-- -----------------------------------------------------
-- MONITOR CONFIGURATION (LAPTOP TEMPLATE)
-- -----------------------------------------------------
-- Run 'hyprctl monitors all' in your terminal to find your exact display name.
-- Replace the 'eDP-1' below with your actual display name.

-- --- BASIC SETUP ---
-- Format: monitor=name,resolution,position,scale
-- Example: Standard 1080p display (No scaling)
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60",
    position = "0x0",
    scale = "1",
})

-- --- HIGH-DPI SCALING (4K or Retina displays) ---
-- Set scale to 1.5 or 2 to make text readable
-- monitor = eDP-1, 3840x2160@60, 0x0, 2

-- --- EXTERNAL DISPLAYS ---
-- Place the external monitor to the right of your laptop screen
-- monitor = HDMI-A-1, preferred, 1920x0, 1

-- --- MIRRORING (Presentations/Projectors) ---
-- Make the external HDMI mirror the laptop screen
-- monitor = HDMI-A-1, preferred, auto, 1, mirror, eDP-1

-- --- FALLBACK (Keep this uncommented to ensure something always displays) ---
hl.monitor({
    output = "",
    mode = "preferred",
    position = "auto",
    scale = "1",
})

