-- -----------------------------------------------------
-- NVIDIA DRIVER CONFIGURATION (TEMPLATE)
-- -----------------------------------------------------
-- Only required for machines with discrete NVIDIA GPUs.

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.env("LIBVA_DRIVER_NAME", "nvidia")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("GBM_BACKEND", "nvidia-drm")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")

hl.config({
    cursor = {
        no_hardware_cursors = true,
    },
})

