# Host-Specific Visual Overrides Template
# ──────────────────────────────────────────────────────────────────────────────
#  HARDWARE OPTIMIZATIONS
# ──────────────────────────────────────────────────────────────────────────────
misc {
    # Variable Frame Rate (Saves battery on laptop)
    vfr = true
    
    # Variable Refresh Rate (Not supported on most laptops, keep disabled)
    vrr = 0 
    
    # Essential HUD settings
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    animate_manual_resizes = true
    animate_mouse_windowdragging = true
}

render {
    direct_scanout = 0
}
