# Personal Window Rules Template
# ──────────────────────────────────────────────────────────────────────────────
#  SPECIAL APPS AUTOMATION
# ──────────────────────────────────────────────────────────────────────────────
# windowrulev2 = workspace special:work, class:^(code-url-handler)$
# windowrulev2 = workspace special:hobby, class:^(Spotify)$
