-- Host-Specific Visual Overrides Template
-- ──────────────────────────────────────────────────────────────────────────────
-- Purpose: Override core visuals if this specific machine has weak hardware.
-- ──────────────────────────────────────────────────────────────────────────────

-- --- PERFORMANCE TWEAKS FOR WEAK LAPTOPS ---
-- Uncomment the blocks below if your donor laptop lags.

-- decoration {
--     blur {
--         enabled = false    # Disabling blur saves a massive amount of GPU power
--     }
--     drop_shadow = false    # Disabling shadows helps performance
-- }

-- animations {
--     enabled = false        # Turns off all animations for an instant, snappy feel
-- }

-- ──────────────────────────────────────────────────────────────────────────────
--  HARDWARE OPTIMIZATIONS
-- ──────────────────────────────────────────────────────────────────────────────
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.config({
    misc = {
        -- Variable Frame Rate (Saves battery on laptop)
        -- vfr = true (deprecated in newer hyprland versions, always enabled)
        -- Variable Refresh Rate (Not supported on most laptops, keep disabled)
        vrr = 0,
        -- Essential HUD settings
        force_default_wallpaper = 0,
        disable_hyprland_logo = true,
        animate_manual_resizes = true,
        animate_mouse_windowdragging = true,
    },
    render = {
        direct_scanout = 0,
    },
})

