-- -----------------------------------------------------
-- AUTOSTART & SERVICES
-- -----------------------------------------------------

-- --- CORE SERVICES ---
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- --- CLIPBOARD & SCRIPTS ---

-- Note: Personalized Apps and Trays should be placed in your host-specific 
-- override file (e.g. hosts/your-host/hypr-host.conf) so they don't break 
-- other users' setups!

hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE")
    hl.exec_cmd("/usr/lib/hyprpolkitagent/hyprpolkitagent")
    hl.exec_cmd("/usr/bin/gnome-keyring-daemon --start --components=secrets")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("hyprsunset")
    hl.exec_cmd("nm-applet --indicator &")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("~/.config/hypr/scripts/xhost-root.sh")
    hl.exec_cmd("~/.config/hypr/scripts/wallpaper-selector.sh --init")
    hl.exec_cmd("killall waybar; waybar")
    hl.exec_cmd("~/.config/hypr/scripts/portal-watcher.sh")
end)

