$color0 = rgb(0f100f)
$color1 = rgb(9F57A1)
$color2 = rgb(8D928A)
$color3 = rgb(9AA896)
$color4 = rgb(A4A5A1)
$color5 = rgb(A8AEA6)
$color6 = rgb(BFC5BB)
$color7 = rgb(e4e6e3)
$color8 = rgb(9fa19e)
$color9 = rgb(9F57A1)
$color10 = rgb(8D928A)
$color11 = rgb(9AA896)
$color12 = rgb(A4A5A1)
$color13 = rgb(A8AEA6)
$color14 = rgb(BFC5BB)
$color15 = rgb(e4e6e3)
$background = rgb(0f100f)
$foreground = rgb(e4e6e3)
$cursor = rgb(e4e6e3)
