-- -----------------------------------------------------
-- INPUT DEVICES (Fallback Kit)
-- -----------------------------------------------------

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace",
})

-- Source: ~/.config/hypr/modules/keyboard.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("modules.keyboard")
hl.config({
    input = {
        follow_mouse = 1,
        sensitivity = 0,
        touchpad = {
            natural_scroll = true,
        },
    },
    -- Keyboard Layout (Dynamically generated by installer from profile.conf)
})

