-- -----------------------------------------------------
-- INPUT DEVICES (Fallback Kit)
-- -----------------------------------------------------

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace",
})

-- Keyboard Layout (Dynamically generated by installer from profile.conf)
require("modules.keyboard")
hl.config({
    input = {
        follow_mouse = 1,
        sensitivity = 0,
        touchpad = {
            natural_scroll = true,
        },
    },
    misc = {
        mouse_move_enables_dpms = true,
        key_press_enables_dpms = true,
    },
})

