-- -----------------------------------------------------
-- KEYBINDINGS :: TITAN CLUSTER
-- -----------------------------------------------------

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- global mainMod is provided by hyprland.lua
-- ──────────────────────────────────────────────────────────────────────────────
--  CLUSTER 1: THE LAUNCHPAD (Top Left: Q-E-R)
-- ──────────────────────────────────────────────────────────────────────────────
hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + CTRL + R", hl.dsp.exec_cmd(runner))
hl.bind(mainMod .. " + ALT + code:61", hl.dsp.exec_cmd("~/.config/hypr/scripts/keybinds-hint.sh"))
-- bind = , XF86Launch1, exec, rofi -show drun

-- W = Wallpaper Selector
hl.bind(mainMod .. " + ALT + W", hl.dsp.exec_cmd("~/.config/hypr/scripts/wallpaper-selector.sh"))
-- E = Effects Menu
hl.bind(mainMod .. " + ALT + E", hl.dsp.exec_cmd("~/.config/hypr/scripts/wallpaper-effects.sh"))

-- ──────────────────────────────────────────────────────────────────────────────
--  CLUSTER 2: THE BUCKETS (Home Row Special Workspaces) [TEMPLATE]
--  "Left hand controls the workspace."
--  These are personal mappings for 'Special Workspaces' using Home Row keys.
--  Uncomment and customize in your local user-keybinds.conf if needed.
-- ──────────────────────────────────────────────────────────────────────────────
-- bind = $mainMod, code:39, togglespecialworkspace, standard        # code:39 = S
-- bind = $mainMod SHIFT, code:39, movetoworkspace, special:standard
-- 
-- bind = $mainMod, code:25, togglespecialworkspace, work            # code:25 = W
-- bind = $mainMod SHIFT, code:25, movetoworkspace, special:work
-- 
-- bind = $mainMod, code:43, togglespecialworkspace, hobby           # code:43 = H
-- bind = $mainMod SHIFT, code:43, movetoworkspace, special:hobby
-- 
-- bind = $mainMod, code:42, togglespecialworkspace, gaming          # code:42 = G
-- bind = $mainMod SHIFT, code:42, movetoworkspace, special:gaming
-- 
-- bind = $mainMod, code:28, togglespecialworkspace, tools           # code:28 = T
-- bind = $mainMod SHIFT, code:28, movetoworkspace, special:tools
-- ──────────────────────────────────────────────────────────────────────────────
--  CLUSTER 3: WINDOW STATE (Bottom Left: Z-X-C-V)
-- ──────────────────────────────────────────────────────────────────────────────
hl.bind(mainMod .. " + C", hl.dsp.window.close())
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))

-- ──────────────────────────────────────────────────────────────────────────────
--  CLUSTER 4: SYSTEM (Protected / Right Hand)
-- ──────────────────────────────────────────────────────────────────────────────
hl.bind(mainMod .. " + L", hl.dsp.exec_cmd("hyprlock"))
-- [ hardware-trigger ] Power Menu bind moved to host vault
hl.bind("CTRL + SHIFT + S", hl.dsp.exec_cmd("~/.config/hypr/scripts/screenshot-swappy.sh"))
hl.bind("Print", hl.dsp.exec_cmd("grim - | wl-copy"))
hl.bind(mainMod .. " + SHIFT + V", hl.dsp.exec_cmd("~/.config/hypr/scripts/cliphist-rofi.sh"))
hl.bind(mainMod .. " + N", hl.dsp.exec_cmd("swaync-client -t -sw"))
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd("~/.config/waybar/scripts/power_cycle.sh"))
hl.bind(mainMod .. " + ALT + B", hl.dsp.exec_cmd("~/.config/hypr/scripts/waybar-switcher.sh"))
hl.bind(mainMod .. " + SHIFT + E", hl.dsp.exec_cmd("~/.config/hypr/scripts/pilot-hydra.py"))
-- ──────────────────────────────────────────────────────────────────────────────
--  CLUSTER 5: NAVIGATION (Arrows & Standard 1-10)
-- ──────────────────────────────────────────────────────────────────────────────
hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))

hl.bind(mainMod .. " + code:10", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + code:11", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + code:12", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + code:13", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + code:14", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + code:15", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + code:16", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + code:17", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + code:18", hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + code:19", hl.dsp.focus({ workspace = 10 }))

hl.bind(mainMod .. " + SHIFT + code:10", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + SHIFT + code:11", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + SHIFT + code:12", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + SHIFT + code:13", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + SHIFT + code:14", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + SHIFT + code:15", hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + SHIFT + code:16", hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + SHIFT + code:17", hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + SHIFT + code:18", hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainMod .. " + SHIFT + code:19", hl.dsp.window.move({ workspace = 10 }))

-- ──────────────────────────────────────────────────────────────────────────────
--  CLUSTER 6: EXPANDED WORKSPACES (F1-F12 -> 11-22) [TEMPLATE]
--  Uncomment and customize in your local user-keybinds.conf if needed.
-- ──────────────────────────────────────────────────────────────────────────────
-- bind = $mainMod, code:67, workspace, 11            # code:67 = F1
-- bind = $mainMod, code:68, workspace, 12            # code:68 = F2
-- bind = $mainMod, code:69, workspace, 13            # code:69 = F3
-- bind = $mainMod, code:70, workspace, 14            # code:70 = F4
-- bind = $mainMod, code:71, workspace, 15            # code:71 = F5
-- bind = $mainMod, code:72, workspace, 16            # code:72 = F6
-- bind = $mainMod, code:73, workspace, 17            # code:73 = F7
-- bind = $mainMod, code:74, workspace, 18            # code:74 = F8
-- bind = $mainMod, code:75, workspace, 19            # code:75 = F9
-- bind = $mainMod, code:76, workspace, 20            # code:76 = F10
-- bind = $mainMod, code:95, workspace, 21            # code:95 = F11
-- bind = $mainMod, code:96, workspace, 22            # code:96 = F12
-- ──────────────────────────────────────────────────────────────────────────────

-- [ hardware-trigger ] Media & Audio binds moved to host vault

-- Mouse Interaction
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())
