-- -----------------------------------------------------
-- VISUALS & ANIMATIONS (Pywal Integrated)
-- -----------------------------------------------------

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: ~/.config/hypr/modules/colors.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("modules.colors")

-- ──────────────────────────────────────────────────────────────────────────────
--  GENERAL HUD LAYOUT [TEMPLATE]
--  Standard gaps and border behavior. Override in user-visuals.conf.
-- ──────────────────────────────────────────────────────────────────────────────
-- general {
--     gaps_in = 5
--     gaps_out = 15
--     border_size = 2
-- }

hl.curve("overshot", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })
hl.curve("smoothOut", { type = "bezier", points = { { 0.36, 0 }, { 0.66, -0.56 } } })
hl.curve("smoothIn", { type = "bezier", points = { { 0.25, 1 }, { 0.5, 1 } } })
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 5,
    bezier = "overshot",
    style = "slide",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 4,
    bezier = "smoothOut",
    style = "slide",
})
hl.animation({
    leaf = "windowsMove",
    enabled = true,
    speed = 4,
    bezier = "default",
})
hl.animation({
    leaf = "border",
    enabled = true,
    speed = 10,
    bezier = "default",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 10,
    bezier = "smoothIn",
})
hl.animation({
    leaf = "fadeDim",
    enabled = true,
    speed = 10,
    bezier = "smoothIn",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 6,
    bezier = "default",
})

hl.config({
    general = {
        col = {
            active_border = {
                colors = { color6, color4 },
                angle = 45,
            },
            inactive_border = color0,
        },
        resize_on_border = true,
        allow_tearing = false, -- Logic hook for user-windowrules.conf
        layout = "dwindle",
    },
    -- ──────────────────────────────────────────────────────────────────────────────
    --  DECORATION & OPACITY [TEMPLATE]
    --  Rounding and transparency levels. Override in user-visuals.conf.
    -- ──────────────────────────────────────────────────────────────────────────────
    -- decoration {
    --     rounding = 10
    --     active_opacity = 0.90
    --     inactive_opacity = 0.80
    -- }
    decoration = {
        shadow = {
            enabled = true,
            range = 15,
            render_power = 3,
            color = "rgba(1a1a1aee)",
        },
        blur = {
            enabled = true,
            size = 8,
            passes = 3,
            new_optimizations = true,
            ignore_opacity = true,
            xray = false,
            vibrancy = 0.22,
        },
        dim_inactive = false,
    },
    animations = {
        enabled = true,
    },
    dwindle = {
        preserve_split = true,
    },
    -- ──────────────────────────────────────────────────────────────────────────────
    --  HOST-SPECIFIC TUNING [TEMPLATE]
    --  Machine-specific rendering and hardware optimizations (VRR, VFR, Rendering).
    --  Uncomment and customize in your local user-visuals.conf.
    -- ──────────────────────────────────────────────────────────────────────────────
    -- misc {
    --     vrr = 0 
    -- }
    -- 
    -- render {
    --     direct_scanout = 0
    -- }
})

