-- -----------------------------------------------------
-- WINDOW RULES
-- -----------------------------------------------------

-- --- GAME RULES [TEMPLATE] ---
-- For niche high-performance gaming (Tearing/Immediate Mode).
-- 1. Use 'hyprctl clients' to find the binary class.
-- 2. Add 'windowrule = immediate 1, match:class ^(your_game_here)$' below.
-- 3. Ensure 'allow_tearing = true' is set in your user-visuals.conf.
-- ──────────────────────────────────────────────────────────────────────────────
--  Uncomment and customize in your local user-windowrules.conf.
-- ──────────────────────────────────────────────────────────────────────────────
-- hl.window_rule({ match = { class = "^(payday2_win32_release.exe)$" }, immediate = true })
-- hl.window_rule({ match = { class = "^(steam_app_\\d+)$" }, immediate = true })

-- --- WORKSPACE RULES ---
-- Smart gaps (No gaps when only 1 window)
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.workspace_rule({
    workspace = "w[tv1]",
    gaps_out = 0,
    gaps_in = 0,
    no_border = true,
})

hl.workspace_rule({
    workspace = "f[1]",
    gaps_out = 0,
    gaps_in = 0,
    no_border = true,
})

-- --- SPECIAL APPS AUTOMATION [TEMPLATE] ---
-- Force specific apps to workspaces or set silent launch rules here.
-- Uncomment and customize in your local user-windowrules.conf.
-- ──────────────────────────────────────────────────────────────────────────────
-- hl.window_rule({ match = { class = "^(code-url-handler)$" }, workspace = "special:work" })
-- hl.window_rule({ match = { class = "^(Spotify)$" }, workspace = "special:hobby" })
