# -----------------------------------------------------
# HYPRLOCK HOST OVERRIDES
# -----------------------------------------------------
# Put host-specific overrides here. 
# Example: Different monitor alignments.
