-- DESKTOP SPECIFIC CONFIG
-- -----------------------

-- 1. Input: Hardware Quirks
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.config({
    input = {
        sensitivity = 0,
    },
    -- 3. Desktop Keybinds
    -- (Add any macro keys or specific desktop tools here)
    -- --- HOST-SPECIFIC ENVIRONMENT VARIABLES ---
    -- Example: Force screencasting to use Shared Memory (SHM) to fix EGL_BAD_MATCH CPU spikes on Intel
    -- env = XDG_DESKTOP_PORTAL_HYPRLAND_FORCE_SHM,1
})

