-- -----------------------------------------------------
-- MONITOR CONFIGURATION (DESKTOP TEMPLATE)
-- -----------------------------------------------------

-- Main Display (Preferred)
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "",
    mode = "preferred",
    position = "auto",
    scale = "1",
})

-- Example Dual Monitor Setup
-- monitor = DP-1, 2560x1440@144, 0x0, 1
-- monitor = DP-2, 2560x1440@144, 2560x0, 1
