-- -----------------------------------------------------
-- TITANFALL HYPRLAND MASTER CONFIG
-- -----------------------------------------------------

-- 1. GLOBAL VARIABLES (Must be defined first)
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

mainMod = "SUPER"
terminal = "kitty"
fileManager = "thunar"
menu = "rofi -show drun -terminal kitty -theme ~/.config/rofi/themes/launcher.rasi"
runner = "rofi -show run  -terminal kitty -theme ~/.config/rofi/themes/runner.rasi"

-- 2. MONITOR CONFIGURATION (Dynamically generated by installer)
-- Source: ~/.config/hypr/modules/monitor.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("modules.monitor")

-- 3. ENVIRONMENT VARIABLES
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("GDK_BACKEND", "wayland,x11,*")
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("SDL_VIDEODRIVER", "wayland")
hl.env("CLUTTER_BACKEND", "wayland")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("XDG_MENU_PREFIX", "arch-")

-- Source dynamic NVIDIA environment variables (if GPU detected)
-- Source: ~/.config/hypr/modules/nvidia.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("modules.nvidia")

-- 4. SOURCE MODULES (Load the components)
-- Source: ~/.config/hypr/modules/autostart.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("modules.autostart")
-- Source: ~/.config/hypr/modules/visuals.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("modules.visuals")
-- Source: ~/.config/hypr/modules/input.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("modules.input")
-- Source: ~/.config/hypr/modules/windowrules.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("modules.windowrules")
-- Source: ~/.config/hypr/modules/keybinds.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("modules.keybinds")

-- 5. HOST SPECIFIC OVERRIDES (Last to override defaults)
-- Source: ~/.config/hypr/host.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("host")

-- 6. USER OVERRIDES (Absolute highest priority)
-- Source: ~/.config/hypr/user-keybinds.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("user-keybinds")
-- Source: ~/.config/hypr/user-windowrules.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("user-windowrules")
-- Source: ~/.config/hypr/user-visuals.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("user-visuals")
