-- -----------------------------------------------------
-- TITANFALL HYPRLAND MASTER CONFIG
-- -----------------------------------------------------

-- 1. GLOBAL VARIABLES (Must be defined first)
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

mainMod = "SUPER"
terminal = "kitty"
fileManager = "thunar"
menu = "rofi -show drun -terminal kitty -theme ~/.config/rofi/themes/launcher.rasi"
runner = "rofi -show run  -terminal kitty -theme ~/.config/rofi/themes/runner.rasi"

-- 2. MONITOR CONFIGURATION (Dynamically generated by installer)
require("modules.monitor")

-- 3. ENVIRONMENT VARIABLES
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("GDK_BACKEND", "wayland,x11,*")
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("SDL_VIDEODRIVER", "wayland")
hl.env("CLUTTER_BACKEND", "wayland")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("XDG_MENU_PREFIX", "arch-")

-- Source dynamic NVIDIA configuration (if GPU detected)
require("modules.nvidia")

-- 4. SOURCE MODULES (Core components)
require("modules.autostart")
require("modules.visuals")
require("modules.input")
require("modules.windowrules")
require("modules.keybinds")

-- 5. HOST SPECIFIC OVERRIDES (Hardware-specific profiles)
require("host")

-- 6. USER OVERRIDES (Absolute highest priority)
require("user-keybinds")
require("user-windowrules")
require("user-visuals")
